// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagDetailVo } from "./TagDetailVo";

export type PerformerDetailVo = { id: number, name: string, rating: number, country: string | null, imagePath: string | null, tags: Array<TagDetailVo>, };
