// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoProbeDetailVo = {
  path: string;
  title: string;
  subtitle: string | null;
  performers: Array<string>;
  studio: string | null;
  code: string | null;
  tags: Array<string>;
  country: string;
  duration: number;
  width: number;
  height: number;
  base64Cover: string | null;
  size: number;
  rating: string | null;
};
